Fix #126
GlodBlock/AE2FluidCraft-Rework pull request #128
Opened 2023-12-15 12:30 UTC by zeng-github01

2023-12-17 06:40 UTC, GlodBlock requested changes

2023-12-17 06:40 UTC, GlodBlock commented on src/main/java/com/glodblock/github/common/tile/TileFluidLevelMaintainer.java
> +    public EnumFacing facing = EnumFacing.NORTH;
这个字段要保存进nbt，不然每次重进游戏就丢失了

2023-12-17 14:57 UTC, zeng-github01 commented on src/main/java/com/glodblock/github/common/tile/TileFluidLevelMaintainer.java
> +    public EnumFacing facing = EnumFacing.NORTH;
nbt不是方块数据吗？Tile里的数据就是当前方块的吧？会丢

2023-12-17 15:00 UTC, GlodBlock commented on src/main/java/com/glodblock/github/common/tile/TileFluidLevelMaintainer.java
> +    public EnumFacing facing = EnumFacing.NORTH;
nbt是就是tile存进硬盘的额外数据，你要手动保存和加载，方块存的是blockstate

2023-12-17 15:02 UTC, zeng-github01 commented on src/main/java/com/glodblock/github/common/tile/TileFluidLevelMaintainer.java
> +    public EnumFacing facing = EnumFacing.NORTH;
想起来了，确实大部分的Tile都有两个nbt的读写方法。等我明天去其他插件那里借鉴一下

2023-12-17 15:10 UTC, zeng-github01 commented on src/main/java/com/glodblock/github/common/tile/TileFluidLevelMaintainer.java
> +    public EnumFacing facing = EnumFacing.NORTH;
> nbt是就是tile存进硬盘的额外数据，你要手动保存和加载，方块存的是blockstate

对了，还需要问一下，修改这个审查涉及的代码的方式，是我弄一个新的提交吗？还是GitHub自己有什么功能，手机版看到有一个解决。不知道按下去会怎么样。

2023-12-17 15:42 UTC, GlodBlock commented on src/main/java/com/glodblock/github/common/tile/TileFluidLevelMaintainer.java
> +    public EnumFacing facing = EnumFacing.NORTH;
你就正常提交commit

2023-12-18 00:40 UTC, zeng-github01 commented on src/main/java/com/glodblock/github/common/tile/TileFluidLevelMaintainer.java
> +    public EnumFacing facing = EnumFacing.NORTH;
已提交补丁，本地测试中

2023-12-18 01:52 UTC, zeng-github01 commented on src/main/java/com/glodblock/github/common/tile/TileFluidLevelMaintainer.java
> +    public EnumFacing facing = EnumFacing.NORTH;
nbt的解析出了一点问题，重新打了个补丁，这下可以了

2023-12-18 02:30 UTC, zeng-github01 commented
@GlodBlock 额外加了一个补丁，简单的让这个方块可以旋转

2023-12-18 07:51 UTC, zeng-github01 commented
@GlodBlock 目前在改写blockstate的json文件，留一个支持未激活状态下的正面纹理的位置。作者方便说一下什么算激活吗，我好在那里改state。比如能否获取频道的方法。目前是把未激活的纹理留空，然后激活状态固定为true。手上的模型会出bug，暂时放弃挣扎

2023-12-18 08:55 UTC, GlodBlock commented
你指什么激活

2023-12-18 09:22 UTC, zeng-github01 commented
> 你指什么激活

原版的懒人AE的话，如果没入网，正面的纹理是熄灭的，像是没开机一样。我想实现这个功能。不过目前没有找到解决方案。就先这样用着吧。现有的功能已经可以

2023-12-18 09:25 UTC, merged